const express = require("express");
const { Pool } = require("pg");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const cookieParser = require("cookie-parser");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const path = require("path");
const crypto = require("crypto");

const app = express();
const PORT = process.env.PORT || 3000;

const JWT_SECRET = process.env.JWT_SECRET || crypto.randomBytes(32).toString("hex");
if (process.env.NODE_ENV === "production" &&
    (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32)) {
  throw new Error("JWT_SECRET must be set to a random secret of at least 32 characters in production.");
}

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set to connect to Supabase/PostgreSQL.");
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
  max: 5
});

app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: "100kb" }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));
app.use(rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 200,
  standardHeaders: true,
  legacyHeaders: false
}));

async function initDb() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users(
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      pin_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );

    CREATE TABLE IF NOT EXISTS customers(
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT,
      debt_cents INTEGER NOT NULL,
      paid_cents INTEGER NOT NULL DEFAULT 0,
      archived INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL,
      plates_count INTEGER NOT NULL DEFAULT 0,
      drinks_count INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS payments(
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
      amount_cents INTEGER NOT NULL,
      created_at TIMESTAMPTZ NOT NULL
    );
  `);

  const { rows } = await pool.query("SELECT COUNT(*)::int AS c FROM users");
  if (rows[0].c === 0) {
    const adminPin = process.env.ADMIN_PIN;
    if (!adminPin || !/^\d{4,6}$/.test(adminPin)) {
      throw new Error("ADMIN_PIN must be set to the existing 4-6 digit admin PIN before the first Supabase startup.");
    }
    await pool.query(
      "INSERT INTO users(name,pin_hash,created_at) VALUES($1,$2,$3)",
      ["Lovely Pierre", bcrypt.hashSync(adminPin, 12), new Date()]
    );
  }
}

function auth(req, res, next) {
  const token = req.cookies.session;
  try {
    const p = jwt.verify(token, JWT_SECRET);
    req.user = p;
    next();
  } catch {
    return res.status(401).json({ error: "Sesyon an fini. Konekte ankò." });
  }
}

app.post("/api/login", async (req, res) => {
  try {
    const pin = String(req.body.pin || "");
    const { rows } = await pool.query("SELECT * FROM users WHERE id=1");
    const u = rows[0];

    if (!u || !/^\d{4,6}$/.test(pin) || !bcrypt.compareSync(pin, u.pin_hash)) {
      return res.status(401).json({ error: "PIN lan pa bon." });
    }

    const token = jwt.sign(
      { id: u.id, name: u.name },
      JWT_SECRET,
      { expiresIn: "8h" }
    );

    res.cookie("session", token, {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 8 * 60 * 60 * 1000
    });

    res.json({ name: u.name });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè sèvè." });
  }
});

app.post("/api/logout", (req, res) => {
  res.clearCookie("session");
  res.json({ ok: true });
});

app.get("/api/me", auth, (req, res) => {
  res.json({ name: req.user.name });
});

app.get("/api/customers", auth, async (req, res) => {
  try {
    const { rows } = await pool.query(`
      SELECT c.*,
             COALESCE(SUM(p.amount_cents),0)::bigint AS paid_from_payments
      FROM customers c
      LEFT JOIN payments p ON p.customer_id=c.id
      GROUP BY c.id
      ORDER BY c.created_at DESC
    `);

    res.json(rows.map(c => ({
      ...c,
      paid_cents: Number(c.paid_cents),
      remaining_cents: Math.max(0, Number(c.debt_cents) - Number(c.paid_cents))
    })));
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan chaje kliyan yo." });
  }
});

app.post("/api/customers", auth, async (req, res) => {
  try {
    const name = String(req.body.name || "").trim();
    const phone = String(req.body.phone || "").trim();
    const debt = Number(req.body.debt);
    const plates = Math.max(0, Math.floor(Number(req.body.plates_count || 0)));
    const drinks = Math.max(0, Math.floor(Number(req.body.drinks_count || 0)));

    if (!name || !Number.isFinite(debt) || debt <= 0) {
      return res.status(400).json({ error: "Non ak montan an obligatwa." });
    }

    if (!Number.isFinite(plates) || !Number.isFinite(drinks)) {
      return res.status(400).json({ error: "Kantite yo pa valab." });
    }

    const cents = Math.round(debt * 100);

    const { rows } = await pool.query(
      `INSERT INTO customers
       (name,phone,debt_cents,plates_count,drinks_count,created_at)
       VALUES($1,$2,$3,$4,$5,$6)
       RETURNING id`,
      [name, phone, cents, plates, drinks, new Date()]
    );

    res.json({ id: rows[0].id });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan ajoute kliyan an." });
  }
});

app.post("/api/customers/:id/payments", auth, async (req, res) => {
  const client = await pool.connect();

  try {
    const id = Number(req.params.id);
    const amount = Number(req.body.amount);

    await client.query("BEGIN");

    const { rows } = await client.query(
      "SELECT * FROM customers WHERE id=$1 FOR UPDATE",
      [id]
    );

    const c = rows[0];

    if (!c || c.archived) {
      await client.query("ROLLBACK");
      return res.status(404).json({ error: "Kliyan an pa disponib." });
    }

    const cents = Math.round(amount * 100);
    const remaining = Number(c.debt_cents) - Number(c.paid_cents);

    if (!Number.isFinite(amount) || cents <= 0 || cents > remaining) {
      await client.query("ROLLBACK");
      return res.status(400).json({ error: "Montan peman an pa valab." });
    }

    await client.query(
      "INSERT INTO payments(customer_id,amount_cents,created_at) VALUES($1,$2,$3)",
      [id, cents, new Date()]
    );

    await client.query(
      "UPDATE customers SET paid_cents=paid_cents+$1 WHERE id=$2",
      [cents, id]
    );

    const afterResult = await client.query(
      "SELECT debt_cents,paid_cents FROM customers WHERE id=$1",
      [id]
    );

    const after = afterResult.rows[0];

    if (Number(after.debt_cents) === Number(after.paid_cents)) {
      await client.query(
        "UPDATE customers SET archived=1 WHERE id=$1",
        [id]
      );
    }

    await client.query("COMMIT");

    res.json({
      ok: true,
      remaining_cents: Math.max(
        0,
        Number(after.debt_cents) - Number(after.paid_cents)
      )
    });
  } catch (e) {
    await client.query("ROLLBACK").catch(() => {});
    console.error(e);
    res.status(500).json({ error: "Erè nan anrejistre peman an." });
  } finally {
    client.release();
  }
});

app.patch("/api/customers/:id", auth, async (req, res) => {
  try {
    const id = Number(req.params.id);

    const result = await pool.query(
      "SELECT * FROM customers WHERE id=$1",
      [id]
    );

    const c = result.rows[0];

    if (!c) {
      return res.status(404).json({ error: "Kliyan an pa jwenn." });
    }

    const name = String(req.body.name ?? c.name).trim();
    const phone = String(req.body.phone ?? c.phone ?? "").trim();

    const debt = req.body.debt === undefined
      ? Number(c.debt_cents)
      : Number(req.body.debt) * 100;

    const plates = req.body.plates_count === undefined
      ? Number(c.plates_count)
      : Math.max(0, Math.floor(Number(req.body.plates_count)));

    const drinks = req.body.drinks_count === undefined
      ? Number(c.drinks_count)
      : Math.max(0, Math.floor(Number(req.body.drinks_count)));

    if (!name || !Number.isFinite(debt) || debt < Number(c.paid_cents)) {
      return res.status(400).json({
        error: "Dèt la pa ka pi piti pase sa kliyan an deja peye."
      });
    }

    if (!Number.isFinite(plates) || !Number.isFinite(drinks)) {
      return res.status(400).json({ error: "Kantite yo pa valab." });
    }

    await pool.query(
      `UPDATE customers
       SET name=$1,phone=$2,debt_cents=$3,plates_count=$4,drinks_count=$5
       WHERE id=$6`,
      [name, phone, Math.round(debt), plates, drinks, id]
    );

    res.json({ ok: true });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan modifye kliyan an." });
  }
});

app.delete("/api/customers/:id", auth, async (req, res) => {
  try {
    const id = Number(req.params.id);

    const result = await pool.query(
      "SELECT * FROM customers WHERE id=$1",
      [id]
    );

    const c = result.rows[0];

    if (!c || !c.archived) {
      return res.status(400).json({
        error: "Se sèlman dèt ki fini ki ka efase."
      });
    }

    await pool.query("DELETE FROM customers WHERE id=$1", [id]);

    res.json({ ok: true });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan efase kliyan an." });
  }
});

app.get("/api/customers/:id/payments", auth, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT amount_cents,created_at
       FROM payments
       WHERE customer_id=$1
       ORDER BY created_at DESC`,
      [Number(req.params.id)]
    );

    res.json(rows);
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan chaje peman yo." });
  }
});

app.post("/api/change-pin", auth, async (req, res) => {
  try {
    const old = String(req.body.oldPin || "");
    const next = String(req.body.newPin || "");

    const { rows } = await pool.query(
      "SELECT * FROM users WHERE id=1"
    );

    const u = rows[0];

    if (!u || !bcrypt.compareSync(old, u.pin_hash)) {
      return res.status(401).json({ error: "PIN aktyèl la pa bon." });
    }

    if (!/^\d{4,6}$/.test(next)) {
      return res.status(400).json({
        error: "Nouvo PIN lan dwe gen 4–6 chif."
      });
    }

    await pool.query(
      "UPDATE users SET pin_hash=$1 WHERE id=1",
      [bcrypt.hashSync(next, 12)]
    );

    res.clearCookie("session");
    res.json({ ok: true });
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Erè nan chanje PIN lan." });
  }
});

app.get("/{*splat}", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

async function start() {
  try {
    await initDb();

    app.listen(PORT, () => {
      console.log(`7Perfection Debt Tool running on port ${PORT}`);
    });
  } catch (e) {
    console.error("Database startup error:", e);
    process.exit(1);
  }
}

start();